name: Java Code Auto Format
on: pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run spotless
        run: ./gradlew :spotlessApply

      - name: Check for modified files
        id: git-check
        run: |
          LOCAL=$(git rev-parse HEAD)
          REMOTE=$(git rev-parse origin/main)
          if [ "$LOCAL" == "$REMOTE" ]; then
            echo "::set-output name=up-to-date::true"
          else
            echo "::set-output name=up-to-date::false"
          fi

      - name: Push changes
        if: steps.git-check.outputs.up-to-date == 'false'
        run: |
          git config --global user.name 'Bram van Heuveln'
          git config --global user.email 'bram28@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.AUTO_FORMAT_SECRET }}@github.com/${{ github.repository }}
          git commit -am "Automated Java code formatting changes"
          git push