name: Java Code Auto Format
on: pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
            java-version: 21
            distribution: temurin


      - name: Install spotless
        run: |
          curl -Ls "https://repo.maven.apache.org/maven2/com/diffplug/spotless/spotless-maven-plugin/5.14.2/spotless-maven-plugin-5.14.2.jar" -o spotless.jar

      - name: Run spotless
        run: java -jar spotless.jar apply

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_ENV

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Bram van Heuveln'
          git config --global user.email 'bram28@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.AUTO_FORMAT_SECRET }}@github.com/${{ github.repository }}
          git commit -am "Automated Java code formatting changes"
          git push