name: Run JUnit Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up JDK and Gradle on Linux
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Run JUnit Tests on Linux
        run: |
          ./gradlew test

  test-macos:
    runs-on: macos-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up JDK and Gradle on macOS
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Run JUnit Tests on macOS
        run: |
          ./gradlew test

  test-windows:
    runs-on: windows-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up JDK and Gradle on Windows
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Run JUnit Tests on Windows
        run: |
          .\gradlew.bat test