name: Run JUnit Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run JUnit Tests on Linux
        run: |
          ./gradlew test --tests '*' | grep -E 'Test:|PASSED|FAILED'
          test_result=${PIPESTATUS[0]}
          if [[ $test_result -ne 0 ]]; then
            echo "Tests failed with exit code $test_result"
            exit 1
          fi

  test-macos:
    runs-on: macos-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run JUnit Tests on macOS
        run: |
          ./gradlew test --tests '*' | grep -E 'Test:|PASSED|FAILED'
          test_result=${PIPESTATUS[0]}
          if [[ $test_result -ne 0 ]]; then
            echo "Tests failed with exit code $test_result"
            exit 1
          fi

  test-windows:
    runs-on: windows-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up JDK and Gradle on Windows
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Run JUnit Tests on Windows
        run: |
          ./gradlew.bat test --tests '*' | findstr /C:"Test:" /C:"PASSED" /C:"FAILED"
          test_result=${PIPESTATUS[0]}
          if [[ $test_result -ne 0 ]]; then
            echo "Tests failed with exit code $test_result"
            exit 1
          fi
