name: Java CI with Gradle

on:
  push:
    branches:
      - master, dev
  pull_request:
    branches:
      - master, dev

jobs:
  test:
    runs-on: ubuntu-latest, windows-latest, macos-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Run Gradle Build and Tests
        run: |
          ./gradlew clean build test
